<a href="https://colab.research.google.com/github/girupashankar/Computer_Vision/blob/main/DL_for_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning foor Computer Vision with Python and TensorFlow by neuralean on freecodecamp.org

## Set 1

### Tensorflow Basics

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# tensor_zero_d tensor
= tf.constant(4)
print(tensor_zero_d)
type(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [3]:
# tensor_one_d tensor
tensor_one_d =  tf.constant([2, 3, 4, 5, 6])
print(tensor_one_d)

tf.Tensor([2 3 4 5 6], shape=(5,), dtype=int32)


In [6]:
# tensor_two_d
tensor_two_d = tf.constant([[2,3], [4,5]])
print(tensor_two_d)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [11]:
# tensor_multi_d
tensor_multi_d = tf.constant([
    [[2,3], [3,4],
     [23,33],[4, 5]],
    [[32,44], [2, 5],
     [7,8], [9,9]]
     ])
print(tensor_multi_d)

tf.Tensor(
[[[ 2  3]
  [ 3  4]
  [23 33]
  [ 4  5]]

 [[32 44]
  [ 2  5]
  [ 7  8]
  [ 9  9]]], shape=(2, 4, 2), dtype=int32)


In [15]:
tensor_four_d = tf.constant([
 [[[2,3], [3,4],
     [23,33],[4, 5]],
    [[32,44], [2, 5],
     [7,8], [9,9]]],
  [[[2,3], [3,4],
     [23,33],[4, 5]],
    [[32,44], [2, 5],
     [7,8], [9,9]]]
     ])
print(tensor_four_d)

tf.Tensor(
[[[[ 2  3]
   [ 3  4]
   [23 33]
   [ 4  5]]

  [[32 44]
   [ 2  5]
   [ 7  8]
   [ 9  9]]]


 [[[ 2  3]
   [ 3  4]
   [23 33]
   [ 4  5]]

  [[32 44]
   [ 2  5]
   [ 7  8]
   [ 9  9]]]], shape=(2, 2, 4, 2), dtype=int32)


### Casting

In [17]:
casted_data = tf.cast(tensor_four_d, dtype=tf.quint8)
print(casted_data)

tf.Tensor(
[[[[ 2  3]
   [ 3  4]
   [23 33]
   [ 4  5]]

  [[32 44]
   [ 2  5]
   [ 7  8]
   [ 9  9]]]


 [[[ 2  3]
   [ 3  4]
   [23 33]
   [ 4  5]]

  [[32 44]
   [ 2  5]
   [ 7  8]
   [ 9  9]]]], shape=(2, 2, 4, 2), dtype=quint8)


In [18]:
np_array =  np.array([1, 2, 3, 4, 5])
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)


In [19]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
num = tf.fill([2, 3], 9)
print(num)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [22]:
ones_tensor = tf.ones([2,4])
print(ones_tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


In [23]:
tf_like =tf.ones_like(tensor_four_d)
tf_like

<tf.Tensor: shape=(2, 2, 4, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1],
         [1, 1]]]], dtype=int32)>

In [25]:
tf.random.normal(
    shape=[8,4],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[ 0.15114345,  1.379542  , -1.0367948 ,  0.8538964 ],
       [-0.1005175 ,  0.06856307,  0.61814874,  1.1566314 ],
       [ 1.4536746 ,  1.419122  ,  0.17386259, -0.27413222],
       [ 0.13780724,  2.0099058 ,  2.3457394 ,  0.7018787 ],
       [-0.45614064, -0.21334988, -0.91657555, -0.20353895],
       [ 2.075087  ,  2.118485  , -1.8792347 , -1.2842528 ],
       [ 0.99543875, -0.06927685, -0.0389732 ,  0.23554495],
       [ 0.03244505, -0.44770777, -2.1715758 ,  0.34515947]],
      dtype=float32)>